export {default as Admin} from './admin'
export {default as Court} from './court'
export {default as Index} from './index/'
export {default as Prefecture} from './prefecture'
export {default as Profile} from './profile'
export {default as Dashboard} from './admin/Dashboard'
